{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "dotnet_interactive": {
     "language": "pwsh"
    },
    "polyglot_notebook": {
     "kernelName": "pwsh"
    },
    "vscode": {
     "languageId": "polyglot-notebook"
    }
   },
   "outputs": [],
   "source": [
    "# !! RUN THIS CELL FIRST !! It sets up a global function for use in the rest of the notebook\n",
    "\n",
    "# Here is the convenience function that throws an exception for us \n",
    "function throwFunc { throw \"This is an exception!\" }\n",
    "\n",
    "# This sets it to be available across all the cells in this notebook\n",
    "#!set --name throwFunc --value throwFunc"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Exceptions\n",
    "Exceptions are errors in code that generally halt execution; these are known as terminating exceptions. Such errors can be 'caught' using `try`/`catch` blocks (explained in the next section). \n",
    "\n",
    "The utility function `throwFunc` at the top of this notebook contains a `throw` block which generates an exception manually.\n",
    "\n",
    "Errors generated by a `throw` block are terminating, however errors generated by `Write-Error` cmdlet are not; errors generated by Write-Error are just written to the error output stream (although a terminating error can be forced with the `-ErrorAction stop` parameter)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "dotnet_interactive": {
     "language": "pwsh"
    },
    "polyglot_notebook": {
     "kernelName": "pwsh"
    },
    "vscode": {
     "languageId": "polyglot-notebook"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "+++ throwFunc terminates execution if the exception it throws is not caught +++\n",
      "\u001b[31;1mException: \u001b[0m\n",
      "\u001b[31;1m\u001b[36;1mLine |\u001b[0m\n",
      "\u001b[31;1m\u001b[36;1m\u001b[36;1m   4 | \u001b[0m function throwFunc { \u001b[36;1mthrow \"This is an exception!\"\u001b[0m }\u001b[0m\n",
      "\u001b[31;1m\u001b[36;1m\u001b[36;1m\u001b[0m\u001b[36;1m\u001b[0m\u001b[36;1m     | \u001b[31;1m                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\u001b[0m\n",
      "\u001b[31;1m\u001b[36;1m\u001b[36;1m\u001b[0m\u001b[36;1m\u001b[0m\u001b[36;1m\u001b[31;1m\u001b[31;1m\u001b[36;1m     | \u001b[31;1mThis is an exception!\u001b[0m\n"
     ]
    },
    {
     "ename": "Error",
     "evalue": "Command failed: SubmitCode: \"+++ throwFunc terminates execution if the excepti ...",
     "output_type": "error",
     "traceback": [
      "Command failed: SubmitCode: \"+++ throwFunc terminates execution if the excepti ..."
     ]
    }
   ],
   "source": [
    "\"+++ throwFunc terminates execution if the exception it throws is not caught +++\"\n",
    "throwFunc\n",
    "\"+++ Because a throw block is terminating, this should not print +++\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "dotnet_interactive": {
     "language": "pwsh"
    },
    "polyglot_notebook": {
     "kernelName": "pwsh"
    },
    "vscode": {
     "languageId": "polyglot-notebook"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[31;1mWrite-Error: \u001b[31;1mAn error is written to the error stream...\u001b[0m\n",
      "...but it doesnt stop execution.\n",
      "\u001b[31;1mWrite-Error: \u001b[0m\n",
      "\u001b[31;1m\u001b[36;1mLine |\u001b[0m\n",
      "\u001b[31;1m\u001b[36;1m\u001b[36;1m   3 | \u001b[0m \u001b[36;1mWrite-Error \"This does stop execution though\" -ErrorAction Stop\u001b[0m\n",
      "\u001b[31;1m\u001b[36;1m\u001b[36;1m\u001b[0m\u001b[36;1m\u001b[0m\u001b[36;1m     | \u001b[31;1m ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\u001b[0m\n",
      "\u001b[31;1m\u001b[36;1m\u001b[36;1m\u001b[0m\u001b[36;1m\u001b[0m\u001b[36;1m\u001b[31;1m\u001b[31;1m\u001b[36;1m     | \u001b[31;1mThis does stop execution though\u001b[0m\n"
     ]
    },
    {
     "ename": "Error",
     "evalue": "Command failed: SubmitCode: Write-Error \"An error is written to the error stre ...",
     "output_type": "error",
     "traceback": [
      "Command failed: SubmitCode: Write-Error \"An error is written to the error stre ..."
     ]
    }
   ],
   "source": [
    "Write-Error \"An error is written to the error stream...\"\n",
    "\"...but it doesnt stop execution.\"\n",
    "Write-Error \"This does stop execution though\" -ErrorAction Stop\n",
    "\"+++ This wont print +++\""
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Try/Catch\n",
    "\n",
    "PowerShell handles exceptions using `try`/`catch` blocks.\n",
    "\n",
    "A `try` block runs until a terminating exception is generated, at which point control is passed to the `catch` block in order to process the exception."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "dotnet_interactive": {
     "language": "pwsh"
    },
    "polyglot_notebook": {
     "kernelName": "pwsh"
    },
    "vscode": {
     "languageId": "polyglot-notebook"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "I only get printed if there is a terminating error in the try block\n",
      "\u001b[31;1mException: \u001b[31;1mThis is an exception!\u001b[0m\n"
     ]
    },
    {
     "ename": "Error",
     "evalue": "Command failed: SubmitCode: try { ...",
     "output_type": "error",
     "traceback": [
      "Command failed: SubmitCode: try { ..."
     ]
    }
   ],
   "source": [
    "try {\n",
    "    throwFunc\n",
    "} catch {\n",
    "    Write-Output \"I only get printed if there is a terminating error in the try block\"\n",
    "    Write-Error $_\n",
    "}\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## The Call Stack\n",
    "\n",
    "Functions and cmdlets can call other functions and cmdlets within PowerShell code, but when an exception happens not every function involved will be provided in the exception message. This can make it difficult to  understand the full chain of functions that led to an exception. For example, the below wrapper function `A` contains the throwFunc function which generates a terminating exception, however the functions that led to `A` are not included in the exception message:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "dotnet_interactive": {
     "language": "pwsh"
    },
    "polyglot_notebook": {
     "kernelName": "pwsh"
    },
    "vscode": {
     "languageId": "polyglot-notebook"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[31;1mException: \u001b[0m\n",
      "\u001b[31;1m\u001b[36;1mLine |\u001b[0m\n",
      "\u001b[31;1m\u001b[36;1m\u001b[36;1m   4 | \u001b[0m function throwFunc { \u001b[36;1mthrow \"This is an exception!\"\u001b[0m }\u001b[0m\n",
      "\u001b[31;1m\u001b[36;1m\u001b[36;1m\u001b[0m\u001b[36;1m\u001b[0m\u001b[36;1m     | \u001b[31;1m                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\u001b[0m\n",
      "\u001b[31;1m\u001b[36;1m\u001b[36;1m\u001b[0m\u001b[36;1m\u001b[0m\u001b[36;1m\u001b[31;1m\u001b[31;1m\u001b[36;1m     | \u001b[31;1mThis is an exception!\u001b[0m\n"
     ]
    },
    {
     "ename": "Error",
     "evalue": "Command failed: SubmitCode: function A { ...",
     "output_type": "error",
     "traceback": [
      "Command failed: SubmitCode: function A { ..."
     ]
    }
   ],
   "source": [
    "function A {\n",
    "    throwFunc\n",
    "}\n",
    "function B {\n",
    "    A\n",
    "}\n",
    "function C {\n",
    "    B\n",
    "}\n",
    "C"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "The _call stack_ is a stack structure (so first in firs out) of functions that are currently executing. The `$PSItem` automatic variable contains the full call stack, which can be examined by printing the `ScriptStackTrace` property."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "dotnet_interactive": {
     "language": "pwsh"
    },
    "polyglot_notebook": {
     "kernelName": "pwsh"
    },
    "vscode": {
     "languageId": "polyglot-notebook"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "at throwFunc, <No file>: line 4\r\n",
      "at A, <No file>: line 2\r\n",
      "at B, <No file>: line 5\r\n",
      "at C, <No file>: line 8\r\n",
      "at <ScriptBlock>, <No file>: line 12\r\n"
     ]
    },
    {
     "ename": "Error",
     "evalue": "Command failed: SubmitCode: function A { ...",
     "output_type": "error",
     "traceback": [
      "Command failed: SubmitCode: function A { ..."
     ]
    }
   ],
   "source": [
    "function A {\n",
    "    throwFunc\n",
    "}\n",
    "function B {\n",
    "    A\n",
    "}\n",
    "function C {\n",
    "    B\n",
    "}\n",
    "\n",
    "try {\n",
    "    C\n",
    "} catch {\n",
    "    $PSItem.ScriptStackTrace\n",
    "}"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".NET (C#)",
   "language": "C#",
   "name": ".net-csharp"
  },
  "language_info": {
   "name": "csharp"
  },
  "polyglot_notebook": {
   "kernelInfo": {
    "defaultKernelName": "csharp",
    "items": [
     {
      "aliases": [],
      "name": "csharp"
     }
    ]
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
